on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          path: ${{ github.workspace }}/app

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build Generic8266(ESP-01)
        run: |
          cd ${{ github.workspace }}/app
          pio run -e ESP8266-ESP01
          mv .pio/build/ESP8266-ESP01/firmware.bin mitsubishi2MQTT_ESP8266-ESP01.bin

      - name: Build WEMOS_D1_Mini
        run: |
          cd ${{ github.workspace }}/app
          pio run -e WEMOS_D1_Mini
          mv .pio/build/WEMOS_D1_Mini/firmware.bin mitsubishi2MQTT_WEMOS_D1_Mini.bin

      - name: Build PIO ESP32DEV
        run: |
          cd ${{ github.workspace }}/app
          pio run -e ESP32DEV
          mv .pio/build/ESP32DEV/firmware.bin mitsubishi2MQTT_ESP32DEV_PIO.bin

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Upload esp8266 realease
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/mitsubishi2MQTT_ESP8266-ESP01.bin
          asset_name: mitsubishi2MQTT_inESP8266-ESP01.bin
          asset_content_type: application/bin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload WEMOS_D1_Mini release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/mitsubishi2MQTT_WEMOS_D1_Mini.bin
          asset_name: mitsubishi2MQTT_WEMOS_D1_Mini.bin
          asset_content_type: application/bin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload PIO esp32dev realease
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/mitsubishi2MQTT_ESP32DEV_PIO.bin
          asset_name: mitsubishi2MQTT_ESP32DEV_PIO.bin
          asset_content_type: application/bin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: esp-idf build
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v4.4.6
          target: esp32
          path: app
       
      - name: Rename IDF bin file
        run: |
          sudo mv ${{ github.workspace }}/app/build/mitsubishi2MQTT.bin ${{ github.workspace }}/app/build/mitsubishi2MQTT_ESP32DEV_IDF.bin
      - name: Upload ESP32DEV_IDF release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/mitsubishi2MQTT_ESP32DEV_IDF.bin
          asset_name: mitsubishi2MQTT_ESP32DEV_IDF.bin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
